import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service · Webstew',
  description: 'Webstew Terms of Service — the rules for using our AI website builder, payment terms, content ownership, and limitations of liability.',
}

const EFFECTIVE_DATE = '2026-05-13'
const ENTITY = 'Remodely LLC'
const CONTACT_EMAIL = 'webstew@remodely.ai'
const SITE = 'webstew.net'

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-white text-slate-900 dark:bg-[#09090b] dark:text-white">
      <div className="max-w-3xl mx-auto px-6 py-16 md:py-24">
        <Link
          href="/"
          className="text-sm text-slate-500 hover:text-slate-900 dark:text-zinc-500 dark:hover:text-white mb-8 inline-block"
        >
          ← Back to Webstew
        </Link>
        <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-2">
          Terms of Service
        </h1>
        <p className="text-sm text-slate-500 dark:text-zinc-500 mb-10">
          Effective {EFFECTIVE_DATE}
        </p>

        <div className="prose prose-slate dark:prose-invert max-w-none prose-headings:font-bold prose-headings:tracking-tight prose-h2:text-2xl prose-h2:mt-12 prose-h2:mb-4 prose-h3:text-lg prose-h3:mt-8 prose-h3:mb-3 prose-p:text-base prose-p:leading-relaxed prose-li:text-base prose-a:text-violet-600 dark:prose-a:text-violet-400">

          <p>
            Welcome to Webstew. These Terms of Service ("<strong>Terms</strong>") govern your access to and use of the Webstew website at {SITE}, the Webstew web application, and all related services (collectively, the "<strong>Service</strong>") provided by {ENTITY} ("<strong>Webstew</strong>," "<strong>we</strong>," "<strong>us</strong>"). By creating an account or using the Service, you agree to these Terms.
          </p>

          <p>
            If you do not agree to these Terms, do not use the Service.
          </p>

          <h2 id="service">1. The Service</h2>
          <p>
            Webstew is an AI-assisted website builder. The Service lets you describe a website in natural language and generates static or framework-based source code, hosts previews, and (with your supplied credentials) can deploy generated sites to third-party hosting providers such as Render. The Service includes related tools — a site grader, template library, image and video tools, and form-submission handling for sites you build.
          </p>
          <p>
            We may add, remove, or change features at any time. We may also discontinue the Service in whole or in part. We'll give reasonable notice of material changes when we can.
          </p>

          <h2 id="accounts">2. Your Account</h2>
          <p>
            You must be at least <strong>13 years old</strong> to use the Service (or the minimum age of digital consent in your country, such as 16 in parts of the EU). If you are under 18, you represent that your parent or legal guardian has reviewed and agreed to these Terms on your behalf.
          </p>
          <p>
            You are responsible for keeping your login credentials secure and for all activity that occurs under your account. Notify us immediately at <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> if you suspect unauthorized access.
          </p>
          <p>
            You may not (a) create accounts using automated means, (b) impersonate another person or entity, (c) share your account credentials, or (d) transfer your account to anyone else without our written consent.
          </p>

          <h2 id="content">3. Your Content</h2>

          <h3>3.1 Ownership</h3>
          <p>
            You retain ownership of the prompts you enter and the website code, copy, images, and other content the Service generates for you under your direction ("<strong>Your Content</strong>"). Webstew does not claim ownership of Your Content.
          </p>

          <h3>3.2 License to Webstew</h3>
          <p>
            To operate the Service, you grant Webstew a worldwide, non-exclusive, royalty-free license to host, store, reproduce, transmit, display, and modify Your Content solely as needed to provide the Service to you (including running it through third-party AI providers, displaying it in previews and shareable links, and storing it in our databases). This license ends when you delete Your Content from the Service, except for backups retained per our normal retention policy and copies you have published or shared publicly.
          </p>

          <h3>3.3 AI-generated content</h3>
          <p>
            Output produced by the Service is generated by large language models. The current model providers include, <strong>but are not limited to</strong>, OpenAI, Anthropic, Google (Gemini), and xAI (Grok). We may add, remove, or change model providers at any time as the AI ecosystem evolves and as we expand the Service. AI-generated output may be inaccurate, may infringe third-party rights in rare cases, and may not be unique to you — similar prompts may produce similar output for other users. <strong>You are responsible for reviewing AI output before publishing, deploying, or relying on it.</strong> We make no warranty that AI output is fit for any particular purpose or free of errors.
          </p>

          <h3>3.4 Acceptable use of Your Content</h3>
          <p>You may not use the Service to create, store, share, or deploy content that:</p>
          <ul>
            <li>Violates any law or regulation, infringes intellectual property, or violates someone's privacy or publicity rights;</li>
            <li>Is defamatory, obscene, harassing, threatening, hateful, or discriminatory based on protected characteristics;</li>
            <li>Sexually exploits minors or depicts minors in a sexual context (we report such material to authorities);</li>
            <li>Promotes violence, terrorism, self-harm, illegal drugs, or illegal weapons;</li>
            <li>Is intentionally designed to deceive (phishing, fake-news, fraud, fake reviews, fake stores);</li>
            <li>Contains malicious code or attempts to extract data from the Service, other users, or third parties;</li>
            <li>Pretends to be Webstew, another user, or a real organization without authorization;</li>
            <li>Otherwise violates the rights of others or these Terms.</li>
          </ul>
          <p>
            We may remove content, suspend or terminate accounts, and report users to authorities for violations of this section.
          </p>

          <h2 id="acceptable-use">4. Acceptable Use of the Service</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Reverse engineer, decompile, scrape, or attempt to extract source code, model weights, or training data from the Service except as permitted by applicable law;</li>
            <li>Resell, sublicense, or share access to the Service without our written consent;</li>
            <li>Use the Service to build a competing AI website builder;</li>
            <li>Interfere with or disrupt the Service, the underlying infrastructure, or other users (DoS, vulnerability scanning without prior authorization, automated traffic exceeding documented rate limits);</li>
            <li>Use the Service to send spam or unsolicited marketing email;</li>
            <li>Circumvent any usage limits, paywalls, or anti-abuse measures.</li>
          </ul>

          <h2 id="payment">5. Payment, Plans, and Refunds</h2>

          <h3>5.1 Plans</h3>
          <p>
            Webstew offers free and paid plans. Pricing, included credits, and feature limits for each plan are described on our <Link href="/upgrade">pricing page</Link> and may change with notice.
          </p>

          <h3>5.2 Payment processing</h3>
          <p>
            Paid plans are billed through <a href="https://stripe.com" target="_blank" rel="noopener noreferrer">Stripe</a>. By subscribing, you authorize Stripe to charge your payment method on a recurring basis (monthly or annually, as selected) at the then-current rate plus applicable taxes. Webstew does not store full payment card numbers — Stripe handles all card data under PCI-DSS compliance.
          </p>

          <h3>5.3 Auto-renewal and cancellation</h3>
          <p>
            Subscriptions renew automatically at the end of each billing period unless cancelled before renewal. You can cancel at any time from your account billing settings. Cancellation takes effect at the end of the current paid period; you'll keep access until then.
          </p>

          <h3>5.4 Refund policy</h3>
          <p>
            Except where required by law, fees already paid for past or current billing periods are <strong>non-refundable</strong>. We do not issue refunds for partial-period cancellations, unused credits, or features you didn't use. We may, in our sole discretion, issue a refund for service outages or billing errors.
          </p>

          <h3>5.5 Free trials and credits</h3>
          <p>
            Free credits and free trial periods are promotional and may be discontinued or reduced at any time. Credits do not have monetary value, are non-refundable, and cannot be transferred between accounts.
          </p>

          <h3>5.6 BYO API keys</h3>
          <p>
            The Service supports "bring your own" API keys for some integrations (your Anthropic, OpenAI, Google, Render, or GitHub keys). When you provide your own keys, you are billed directly by those providers under their terms, and you are responsible for managing your usage and costs with them. Webstew is not liable for charges, rate limits, or outages on third-party services.
          </p>

          <h2 id="third-parties">6. Third-Party Services</h2>
          <p>
            The Service uses or interacts with third-party services. The categories and examples below are <strong>illustrative and not exhaustive</strong> — we engage additional service providers, sub-processors, and integration partners from time to time as the Service grows and as the AI and cloud ecosystems evolve. We will keep this list reasonably current but may add new providers between updates.
          </p>
          <ul>
            <li><strong>AI providers</strong>: includes OpenAI, Anthropic, Google (Gemini), xAI (Grok), and other large language model, embedding, image, voice, and video providers we may add — for text generation, image processing, transcription, speech, and code generation;</li>
            <li><strong>Hosting and infrastructure</strong>: includes Render (for our own service and for sites you deploy), MongoDB Atlas (database), Cloudflare (DNS, CDN, email routing), Amazon Web Services (email delivery, object storage), and similar providers;</li>
            <li><strong>Payments</strong>: Stripe, and other payment processors we may add for regional coverage or for App Store / Play Store in-app purchases;</li>
            <li><strong>Authentication</strong>: NextAuth, with optional Google, GitHub, and Apple OAuth, plus additional identity providers we may add;</li>
            <li><strong>Email delivery</strong>: AWS Simple Email Service and equivalent SMTP providers for transactional email;</li>
            <li><strong>Integration platforms</strong>: tools that broker user-authorized OAuth connections to third-party services (for example, Composio) so you can connect your own Gmail, Stripe, Calendly, Google Calendar, Slack, Shopify, and similar accounts;</li>
            <li><strong>Optional integrations</strong>: Cloudinary, Stripe Connect, and others you enable.</li>
          </ul>
          <p>
            Your use of any third-party service through Webstew is subject to that third party's own terms and privacy policies. We are not responsible for third-party services. Where we materially change which third-party service categories we use, we will update this page and, where required, give notice through the Service.
          </p>

          <h2 id="deployment">7. Sites You Deploy</h2>
          <p>
            When you use Webstew to deploy a generated site to your own hosting provider (Render, GitHub Pages, or elsewhere) using your supplied credentials, you are entering into a separate relationship with that provider. Webstew has no control over those hosted sites once deployed, and we are not responsible for their availability, security, or compliance.
          </p>
          <p>
            Contact-form submissions on sites you deploy through Webstew may, with your configuration, be routed through our infrastructure for notification delivery. Submissions are stored in our database for retrieval by you in your Webstew account. See our <Link href="/privacy">Privacy Policy</Link> for retention details.
          </p>

          <h2 id="mobile">8. Mobile Apps (iOS and Android)</h2>
          <p>
            When you install and use the Webstew mobile app from the Apple App Store or Google Play (each, an "<strong>App Store</strong>"), these additional terms apply.
          </p>

          <h3>8.1 App Store terms</h3>
          <p>
            Your use of the mobile app is also subject to the applicable App Store's terms of use (including Apple's Licensed Application End User License Agreement and Google Play's Terms of Service). These Terms are between you and Webstew only, not the App Store. The App Store has no obligation to provide support for the mobile app.
          </p>

          <h3>8.2 Apple-specific terms</h3>
          <p>
            If you download our iOS app, you acknowledge: (a) Apple is not a party to these Terms and is not responsible for the iOS app or its content; (b) Apple has no obligation to furnish maintenance or support for the iOS app; (c) Apple is not responsible for addressing any claims you have relating to the iOS app, including product-liability claims, consumer-protection claims, or any claim that the iOS app fails to conform to applicable legal or regulatory requirements; (d) in the event of any third-party claim that the iOS app or your use of it infringes that party's intellectual property rights, Apple is not responsible for the investigation, defense, settlement, or discharge of the claim; (e) Apple and its subsidiaries are <strong>third-party beneficiaries</strong> of these Terms with respect to the iOS app and may enforce them against you; and (f) you represent that you are not located in a U.S.-embargoed country and are not on any U.S. government list of prohibited or restricted parties.
          </p>

          <h3>8.3 In-app purchases</h3>
          <p>
            Some plans and credits may be purchased through the App Store using in-app purchases. In-app purchases are processed by Apple or Google under their own terms; refunds for in-app purchases are administered by the App Store, not Webstew. Subscriptions purchased through an App Store auto-renew unless you cancel through the App Store's subscription management before the renewal date.
          </p>

          <h3>8.4 Mobile permissions</h3>
          <p>
            The mobile app may request permission to access: <strong>microphone</strong> (only when you use voice-driven building — we never listen passively), <strong>camera or photo library</strong> (only when you choose to upload an image), and <strong>push notifications</strong> (so we can tell you when a generation completes or a form submission arrives). You can revoke these permissions at any time in your device settings. The app will continue to function with reduced features.
          </p>

          <h2 id="ip">9. Webstew Intellectual Property</h2>
          <p>
            The Service, including its software, design, trademarks, logos, templates, documentation, and all related intellectual property, is owned by Webstew or its licensors and is protected by copyright, trademark, and other laws. We grant you a limited, non-exclusive, non-transferable license to access and use the Service in accordance with these Terms.
          </p>
          <p>
            "Webstew" and the Webstew logo are trademarks of {ENTITY}. You may not use our marks without our prior written consent.
          </p>

          <h2 id="feedback">10. Feedback</h2>
          <p>
            If you send us suggestions, ideas, or feedback about the Service, you grant Webstew a perpetual, irrevocable, worldwide, royalty-free license to use that feedback for any purpose without obligation to you. We're not asking for confidentiality on feedback — but we appreciate you sending it.
          </p>

          <h2 id="termination">11. Suspension and Termination</h2>
          <p>
            You may cancel your account at any time from account settings. We may suspend or terminate your access (with or without notice, immediately, and at our sole discretion) if we believe you have violated these Terms, infringed others' rights, or created risk for Webstew or other users.
          </p>
          <p>
            On termination: your right to use the Service ends, your subscription ends at the end of the current paid period (no refund), and we may delete Your Content after a reasonable wind-down period. Sections that by their nature survive termination (ownership, license to Feedback, disclaimers, limitation of liability, governing law, dispute resolution) will continue to apply.
          </p>

          <h2 id="disclaimer">12. Disclaimers</h2>
          <p>
            <strong>The Service is provided "as is" and "as available," without warranties of any kind, express or implied.</strong> Webstew disclaims all warranties, including implied warranties of merchantability, fitness for a particular purpose, non-infringement, accuracy, reliability, security, and availability.
          </p>
          <p>
            We do not warrant that: (a) the Service will be uninterrupted, secure, or error-free; (b) AI-generated output will be accurate, reliable, original, or suitable for any particular purpose; (c) defects will be corrected; or (d) the Service is free of viruses or harmful code.
          </p>
          <p>
            Some jurisdictions do not allow exclusion of certain warranties; in those places, our warranties are limited to the minimum extent permitted by law.
          </p>

          <h2 id="liability">13. Limitation of Liability</h2>
          <p>
            <strong>To the maximum extent permitted by law, Webstew, its affiliates, officers, employees, and agents will not be liable for any indirect, incidental, special, consequential, exemplary, or punitive damages</strong>, including loss of profits, revenue, data, goodwill, or other intangible losses, arising out of or related to your use of (or inability to use) the Service, even if we have been advised of the possibility of such damages.
          </p>
          <p>
            <strong>Webstew's total cumulative liability for any claim arising out of or related to the Service or these Terms will not exceed the greater of (a) the total fees you paid Webstew in the twelve (12) months immediately preceding the event giving rise to the claim, or (b) one hundred U.S. dollars ($100).</strong>
          </p>
          <p>
            Some jurisdictions do not allow limitation of certain liability; in those places, our liability is limited to the minimum extent permitted by law.
          </p>

          <h2 id="indemnification">14. Indemnification</h2>
          <p>
            You agree to indemnify, defend, and hold harmless Webstew and its affiliates, officers, employees, and agents from any claim, demand, loss, damage, cost, or expense (including reasonable attorneys' fees) arising out of: (a) your use or misuse of the Service; (b) Your Content; (c) your violation of these Terms; or (d) your violation of any law or the rights of any third party.
          </p>

          <h2 id="dispute">15. Dispute Resolution and Governing Law</h2>

          <h3>15.1 Governing law</h3>
          <p>
            These Terms are governed by the laws of the State of Arizona, United States, without regard to its conflict-of-laws principles. Subject to Section 14.2, any dispute arising out of or related to these Terms or the Service will be brought exclusively in the state or federal courts located in Maricopa County, Arizona, and you consent to personal jurisdiction in those courts.
          </p>

          <h3>15.2 Binding arbitration; class action waiver</h3>
          <p>
            <strong>Any dispute, claim, or controversy arising out of or related to these Terms or the Service will be resolved by binding individual arbitration</strong> administered by the American Arbitration Association under its Consumer Arbitration Rules. The arbitration will be conducted in English in Maricopa County, Arizona, or remotely. Judgment on the arbitrator's award may be entered in any court of competent jurisdiction.
          </p>
          <p>
            <strong>You waive any right to bring claims as a class action, collective action, or representative action.</strong> The arbitrator may not consolidate claims or preside over class proceedings.
          </p>
          <p>
            <strong>Opt-out</strong>: You may opt out of binding arbitration by emailing us at <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> within 30 days of first accepting these Terms with the subject "Arbitration Opt-Out." You must include your full name and account email. Opting out does not affect other parts of these Terms.
          </p>

          <h2 id="changes">16. Changes to These Terms</h2>
          <p>
            We may update these Terms from time to time. If we make material changes, we'll notify you by email (to the address on your account) or in-product before the changes take effect, and we'll update the Effective Date at the top of this page. Your continued use of the Service after the effective date constitutes acceptance of the updated Terms.
          </p>

          <h2 id="export">17. Export, Sanctions, and U.S. Government Users</h2>
          <p>
            You may not use or export the Service in violation of U.S. export laws, including the Export Administration Regulations. You represent that you are not located in, and are not a resident or citizen of, any country or region subject to U.S. sanctions (currently including Cuba, Iran, North Korea, Syria, and the Crimea, Donetsk, and Luhansk regions of Ukraine), and that you are not on any U.S. or other applicable government list of restricted parties.
          </p>

          <h2 id="misc">18. Miscellaneous</h2>
          <p>
            <strong>Entire agreement.</strong> These Terms, together with our <Link href="/privacy">Privacy Policy</Link> and any policies or order documents we reference, are the entire agreement between you and Webstew regarding the Service.
          </p>
          <p>
            <strong>Severability.</strong> If any provision of these Terms is unenforceable, the remaining provisions remain in full force and effect.
          </p>
          <p>
            <strong>No waiver.</strong> Our failure to enforce any provision is not a waiver of our right to enforce it later.
          </p>
          <p>
            <strong>Assignment.</strong> You may not assign these Terms without our prior written consent. We may assign these Terms to an affiliate or to a successor in connection with a merger, acquisition, or sale of assets.
          </p>
          <p>
            <strong>Notices.</strong> We may give notices through the Service, by email to the address on your account, or by posting to this page. You may give us notice by email to <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
          </p>
          <p>
            <strong>Force majeure.</strong> Neither party is liable for delays or failures caused by events beyond reasonable control (natural disasters, war, labor disputes, internet outages, third-party service failures, government action).
          </p>

          <h2 id="contact">19. Contact</h2>
          <p>
            Questions about these Terms? Email <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> or write to:
          </p>
          <p>
            {ENTITY}<br />
            Attn: Legal — Webstew<br />
            Arizona, United States
          </p>

          <hr className="my-10 border-slate-200 dark:border-white/10" />

          <p className="text-xs text-slate-500 dark:text-zinc-500">
            These Terms are a first-draft template and do not constitute legal advice. We recommend you consult licensed counsel before launching a commercial service. © {new Date().getFullYear()} {ENTITY}. All rights reserved.
          </p>
        </div>
      </div>
    </main>
  )
}
