// AUTO-GENERATED from template-build/dashboard-app/ — do not hand-edit.
// Edit the source app there, then regenerate this file.

import type { WebsiteTemplate } from "./index"

export const DASHBOARD_APP_TEMPLATE: WebsiteTemplate = {
  "id": "dashboard-app",
  "name": "SaaS Dashboard App",
  "description": "An admin dashboard: sidebar nav, stat cards, a customers data table, settings form, and a standalone sign-in screen. Next.js — re-skin via globals.css, re-content via lib/site.ts.",
  "category": "app",
  "tags": [
    "app",
    "dashboard",
    "saas",
    "admin",
    "table",
    "auth",
    "nextjs"
  ],
  "preview": "",
  "variables": {},
  "html": "",
  "buildTarget": "nextjs",
  "files": {
    "app/globals.css": "/* ============================================================\n   THEME TOKENS — the customization surface. Change a value\n   here and the whole dashboard re-skins. No markup edits.\n   ============================================================ */\n:root {\n  --bg: #f6f7f9;\n  --surface: #ffffff;\n  --text: #14181f;\n  --muted: #5b6472;\n  --border: #e4e7ec;\n  --primary: #2f6df6;\n  --primary-text: #ffffff;\n  --good: #16a34a;\n  --bad: #dc2626;\n  --radius: 12px;\n  --sidebar-w: 220px;\n  --font: ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, sans-serif;\n}\n\n* { box-sizing: border-box; margin: 0; padding: 0; }\nhtml, body { height: 100%; }\nbody { font-family: var(--font); background: var(--bg); color: var(--text); }\na { color: inherit; text-decoration: none; }\n\n.layout { display: flex; min-height: 100vh; }\n.main { flex: 1; padding: 28px 32px; }\n.muted { color: var(--muted); }\n\n.h1 { font-size: 1.5rem; letter-spacing: -0.02em; margin-bottom: 4px; }\n.h2 { font-size: 1.05rem; margin-bottom: 14px; }\n\n.grid { display: grid; gap: 16px; grid-template-columns: repeat(auto-fit, minmax(190px, 1fr)); }\n.card {\n  background: var(--surface);\n  border: 1px solid var(--border);\n  border-radius: var(--radius);\n  padding: 18px;\n}\n\n.btn {\n  display: inline-block;\n  padding: 10px 18px;\n  border-radius: var(--radius);\n  background: var(--primary);\n  color: var(--primary-text);\n  font-weight: 600;\n  border: 1px solid transparent;\n  cursor: pointer;\n  font-size: 0.95rem;\n}\n.btn-ghost { background: transparent; color: var(--text); border-color: var(--border); }\n\n.field { display: flex; flex-direction: column; gap: 6px; margin-bottom: 14px; }\n.field label { font-size: 0.85rem; font-weight: 600; color: var(--muted); }\n.field input {\n  padding: 10px 12px;\n  border: 1px solid var(--border);\n  border-radius: var(--radius);\n  font: inherit;\n  background: var(--surface);\n  color: var(--text);\n}\n\ntable { width: 100%; border-collapse: collapse; }\nth, td { text-align: left; padding: 12px 14px; border-bottom: 1px solid var(--border); font-size: 0.92rem; }\nth { color: var(--muted); font-weight: 600; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.04em; }\n\n.pill { font-size: 0.78rem; font-weight: 600; padding: 3px 10px; border-radius: 999px; }\n.pill-Active { background: #dcfce7; color: #166534; }\n.pill-Trial { background: #fef9c3; color: #854d0e; }\n.pill-Churned { background: #fee2e2; color: #991b1b; }\n",
    "app/layout.tsx": "import './globals.css'\nimport type { Metadata } from 'next'\n\nexport const metadata: Metadata = {\n  title: 'Dashboard',\n  description: 'A starter admin dashboard.',\n}\n\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang=\"en\">\n      <body>{children}</body>\n    </html>\n  )\n}\n",
    "app/login/page.tsx": "import Link from 'next/link'\nimport { site } from '@/lib/site'\n\n// Standalone sign-in screen — no sidebar. Wire the form to a real auth\n// provider via the builder's \"connect\" step; until then it links through.\nexport default function LoginPage() {\n  return (\n    <div className=\"login-wrap\">\n      <div className=\"card login-card\">\n        <div className=\"login-brand\">{site.name}</div>\n        <h1 className=\"h1\" style={{ fontSize: '1.3rem' }}>Sign in</h1>\n        <p className=\"muted\" style={{ marginBottom: 18 }}>Welcome back.</p>\n\n        <div className=\"field\">\n          <label htmlFor=\"email\">Email</label>\n          <input id=\"email\" name=\"email\" type=\"email\" placeholder=\"you@example.com\" />\n        </div>\n        <div className=\"field\">\n          <label htmlFor=\"password\">Password</label>\n          <input id=\"password\" name=\"password\" type=\"password\" placeholder=\"••••••••\" />\n        </div>\n        <Link href=\"/\" className=\"btn\" style={{ display: 'block', textAlign: 'center' }}>\n          Sign in\n        </Link>\n      </div>\n\n      <style>{`\n        .login-wrap {\n          min-height: 100vh;\n          display: flex;\n          align-items: center;\n          justify-content: center;\n          padding: 20px;\n        }\n        .login-card { width: 100%; max-width: 360px; }\n        .login-brand { font-weight: 700; font-size: 1.1rem; margin-bottom: 18px; }\n      `}</style>\n    </div>\n  )\n}\n",
    "app/page.tsx": "import { Shell } from '@/components/Shell'\nimport { StatCard } from '@/components/StatCard'\nimport { DataTable } from '@/components/DataTable'\nimport { stats, rows } from '@/lib/site'\n\nexport default function OverviewPage() {\n  return (\n    <Shell>\n      <h1 className=\"h1\">Overview</h1>\n      <p className=\"muted\" style={{ marginBottom: 22 }}>\n        A snapshot of how things are going.\n      </p>\n\n      <div className=\"grid\" style={{ marginBottom: 28 }}>\n        {stats.map((s) => (\n          <StatCard key={s.label} stat={s} />\n        ))}\n      </div>\n\n      <h2 className=\"h2\">Recent customers</h2>\n      <DataTable rows={rows} />\n    </Shell>\n  )\n}\n",
    "app/settings/page.tsx": "import { Shell } from '@/components/Shell'\nimport { site } from '@/lib/site'\n\nexport default function SettingsPage() {\n  return (\n    <Shell>\n      <h1 className=\"h1\">Settings</h1>\n      <p className=\"muted\" style={{ marginBottom: 22 }}>\n        Manage your workspace.\n      </p>\n\n      <div className=\"card\" style={{ maxWidth: 460 }}>\n        <h2 className=\"h2\">Workspace</h2>\n        <div className=\"field\">\n          <label htmlFor=\"name\">Workspace name</label>\n          <input id=\"name\" name=\"name\" defaultValue={site.name} />\n        </div>\n        <div className=\"field\">\n          <label htmlFor=\"email\">Billing email</label>\n          <input id=\"email\" name=\"email\" type=\"email\" placeholder=\"you@example.com\" />\n        </div>\n        <button className=\"btn\" type=\"button\">Save changes</button>\n      </div>\n    </Shell>\n  )\n}\n",
    "components/DataTable.tsx": "import type { Row } from '@/lib/site'\n\nexport function DataTable({ rows }: { rows: Row[] }) {\n  return (\n    <div className=\"card\" style={{ padding: 0, overflow: 'hidden' }}>\n      <table>\n        <thead>\n          <tr>\n            <th>Name</th>\n            <th>Email</th>\n            <th>Plan</th>\n            <th>Status</th>\n          </tr>\n        </thead>\n        <tbody>\n          {rows.map((r) => (\n            <tr key={r.email}>\n              <td style={{ fontWeight: 600 }}>{r.name}</td>\n              <td className=\"muted\">{r.email}</td>\n              <td>{r.plan}</td>\n              <td><span className={`pill pill-${r.status}`}>{r.status}</span></td>\n            </tr>\n          ))}\n        </tbody>\n      </table>\n    </div>\n  )\n}\n",
    "components/Shell.tsx": "import Link from 'next/link'\nimport { site } from '@/lib/site'\n\n// Sidebar + main wrapper. Dashboard pages render inside <Shell>; the login\n// page is standalone and skips it.\nexport function Shell({ children }: { children: React.ReactNode }) {\n  return (\n    <div className=\"layout\">\n      <aside className=\"sidebar\">\n        <div className=\"sb-brand\">{site.name}</div>\n        <nav className=\"sb-nav\">\n          {site.nav.map((item) => (\n            <Link key={item.href} href={item.href} className=\"sb-link\">\n              {item.label}\n            </Link>\n          ))}\n        </nav>\n        <Link href=\"/login\" className=\"sb-link sb-signout\">Sign out</Link>\n      </aside>\n      <main className=\"main\">{children}</main>\n      <style>{`\n        .sidebar {\n          width: var(--sidebar-w);\n          flex: none;\n          background: var(--surface);\n          border-right: 1px solid var(--border);\n          padding: 22px 14px;\n          display: flex;\n          flex-direction: column;\n        }\n        .sb-brand { font-weight: 700; font-size: 1.1rem; padding: 4px 10px 18px; }\n        .sb-nav { display: flex; flex-direction: column; gap: 2px; }\n        .sb-link {\n          padding: 9px 10px;\n          border-radius: 8px;\n          color: var(--muted);\n          font-weight: 500;\n          font-size: 0.95rem;\n        }\n        .sb-link:hover { background: var(--bg); color: var(--text); }\n        .sb-signout { margin-top: auto; }\n      `}</style>\n    </div>\n  )\n}\n",
    "components/StatCard.tsx": "import type { Stat } from '@/lib/site'\n\nexport function StatCard({ stat }: { stat: Stat }) {\n  const positive = stat.delta.trim().startsWith('+')\n  return (\n    <div className=\"card\">\n      <div className=\"muted\" style={{ fontSize: '0.85rem' }}>{stat.label}</div>\n      <div style={{ fontSize: '1.6rem', fontWeight: 700, margin: '6px 0 2px' }}>\n        {stat.value}\n      </div>\n      <div style={{ fontSize: '0.85rem', fontWeight: 600, color: positive ? 'var(--good)' : 'var(--bad)' }}>\n        {stat.delta}\n      </div>\n    </div>\n  )\n}\n",
    "lib/site.ts": "// ============================================================\n// APP CONTENT — edit this file to make the dashboard your own.\n// Nav, stats, table rows and copy all read from here.\n// ============================================================\n\nexport const site = {\n  name: 'Dashboard',\n  nav: [\n    { label: 'Overview', href: '/' },\n    { label: 'Settings', href: '/settings' },\n  ],\n}\n\nexport interface Stat {\n  label: string\n  value: string\n  delta: string\n}\n\nexport const stats: Stat[] = [\n  { label: 'Total revenue', value: '$48,210', delta: '+12.4%' },\n  { label: 'Active users', value: '2,318', delta: '+4.1%' },\n  { label: 'Open tickets', value: '17', delta: '-9.0%' },\n  { label: 'Conversion', value: '3.6%', delta: '+0.5%' },\n]\n\nexport interface Row {\n  name: string\n  email: string\n  plan: string\n  status: 'Active' | 'Trial' | 'Churned'\n}\n\nexport const rows: Row[] = [\n  { name: 'Avery Cole', email: 'avery@example.com', plan: 'Pro', status: 'Active' },\n  { name: 'Jordan Lee', email: 'jordan@example.com', plan: 'Starter', status: 'Trial' },\n  { name: 'Sam Rivera', email: 'sam@example.com', plan: 'Scale', status: 'Active' },\n  { name: 'Taylor Quinn', email: 'taylor@example.com', plan: 'Pro', status: 'Churned' },\n  { name: 'Morgan Diaz', email: 'morgan@example.com', plan: 'Starter', status: 'Active' },\n]\n",
    "next-env.d.ts": "/// <reference types=\"next\" />\n/// <reference types=\"next/image-types/global\" />\n\n// NOTE: This file should not be edited\n// see https://nextjs.org/docs/app/building-your-application/configuring/typescript for more information.\n",
    "next.config.mjs": "/** @type {import('next').NextConfig} */\nconst nextConfig = {\n  // Keeps the dev server light enough to boot inside the WebContainer preview.\n  reactStrictMode: true,\n}\n\nexport default nextConfig\n",
    "package.json": "{\n  \"name\": \"dashboard-app\",\n  \"version\": \"1.0.0\",\n  \"private\": true,\n  \"scripts\": {\n    \"dev\": \"next dev\",\n    \"build\": \"next build\",\n    \"start\": \"next start\"\n  },\n  \"dependencies\": {\n    \"next\": \"14.2.18\",\n    \"react\": \"^18.3.1\",\n    \"react-dom\": \"^18.3.1\"\n  },\n  \"devDependencies\": {\n    \"@types/node\": \"^20\",\n    \"@types/react\": \"^18\",\n    \"@types/react-dom\": \"^18\",\n    \"typescript\": \"^5\"\n  }\n}\n",
    "tsconfig.json": "{\n  \"compilerOptions\": {\n    \"target\": \"ES2017\",\n    \"lib\": [\"dom\", \"dom.iterable\", \"esnext\"],\n    \"allowJs\": true,\n    \"skipLibCheck\": true,\n    \"strict\": true,\n    \"noEmit\": true,\n    \"esModuleInterop\": true,\n    \"module\": \"esnext\",\n    \"moduleResolution\": \"bundler\",\n    \"resolveJsonModule\": true,\n    \"isolatedModules\": true,\n    \"jsx\": \"preserve\",\n    \"incremental\": true,\n    \"plugins\": [{ \"name\": \"next\" }],\n    \"paths\": { \"@/*\": [\"./*\"] }\n  },\n  \"include\": [\"next-env.d.ts\", \"**/*.ts\", \"**/*.tsx\", \".next/types/**/*.ts\"],\n  \"exclude\": [\"node_modules\"]\n}\n"
  }
}
