// AUTO-GENERATED from template-build/mobile-app/ — do not hand-edit.
// Edit the source app there, then regenerate this file.

import type { WebsiteTemplate } from "./index"

export const MOBILE_APP_TEMPLATE: WebsiteTemplate = {
  "id": "mobile-app",
  "name": "Mobile App (Expo)",
  "description": "A React Native / Expo starter: bottom-tab navigation, a home feed, an activity/stats screen, and a profile screen with live tab state. Re-skin via src/theme.ts, re-content via src/data.ts.",
  "category": "app",
  "tags": [
    "app",
    "mobile",
    "expo",
    "react-native",
    "ios",
    "android",
    "tabs"
  ],
  "preview": "",
  "variables": {},
  "html": "",
  "buildTarget": "expo",
  "files": {
    "App.tsx": "import { useState } from 'react'\nimport { View, StyleSheet } from 'react-native'\nimport { StatusBar } from 'expo-status-bar'\nimport { theme } from './src/theme'\nimport { tabs, type TabKey } from './src/data'\nimport { TabBar } from './src/components/TabBar'\nimport { HomeScreen } from './src/screens/HomeScreen'\nimport { ActivityScreen } from './src/screens/ActivityScreen'\nimport { ProfileScreen } from './src/screens/ProfileScreen'\n\nexport default function App() {\n  const [tab, setTab] = useState<TabKey>('home')\n  return (\n    <View style={styles.app}>\n      <StatusBar style=\"dark\" />\n      <View style={styles.screen}>\n        {tab === 'home' && <HomeScreen />}\n        {tab === 'activity' && <ActivityScreen />}\n        {tab === 'profile' && <ProfileScreen />}\n      </View>\n      <TabBar tabs={tabs} active={tab} onChange={setTab} />\n    </View>\n  )\n}\n\nconst styles = StyleSheet.create({\n  app: { flex: 1, backgroundColor: theme.bg },\n  screen: { flex: 1 },\n})\n",
    "app.json": "{\n  \"expo\": {\n    \"name\": \"NewLeaf\",\n    \"slug\": \"mobile-app\",\n    \"version\": \"1.0.0\",\n    \"orientation\": \"portrait\",\n    \"userInterfaceStyle\": \"light\",\n    \"newArchEnabled\": true,\n    \"splash\": {\n      \"resizeMode\": \"contain\",\n      \"backgroundColor\": \"#ffffff\"\n    },\n    \"ios\": {\n      \"supportsTablet\": true\n    },\n    \"android\": {\n      \"edgeToEdgeEnabled\": true,\n      \"predictiveBackGestureEnabled\": false\n    },\n    \"web\": {}\n  }\n}\n",
    "index.ts": "import { registerRootComponent } from 'expo';\n\nimport App from './App';\n\n// registerRootComponent calls AppRegistry.registerComponent('main', () => App);\n// It also ensures that whether you load the app in Expo Go or in a native build,\n// the environment is set up appropriately\nregisterRootComponent(App);\n",
    "package.json": "{\n  \"name\": \"mobile-app\",\n  \"version\": \"1.0.0\",\n  \"main\": \"index.ts\",\n  \"scripts\": {\n    \"start\": \"expo start\",\n    \"android\": \"expo start --android\",\n    \"ios\": \"expo start --ios\",\n    \"web\": \"expo start --web\"\n  },\n  \"dependencies\": {\n    \"@expo/metro-runtime\": \"~4.0.1\",\n    \"expo\": \"~52.0.0\",\n    \"expo-asset\": \"~11.0.5\",\n    \"expo-status-bar\": \"~2.0.1\",\n    \"expo-linear-gradient\": \"~14.0.2\",\n    \"react\": \"18.3.1\",\n    \"react-dom\": \"18.3.1\",\n    \"react-native\": \"0.76.9\",\n    \"react-native-web\": \"~0.19.13\"\n  },\n  \"devDependencies\": {\n    \"@types/react\": \"~18.3.12\",\n    \"typescript\": \"~5.3.3\"\n  },\n  \"private\": true\n}\n",
    "src/components/Card.tsx": "import { View, StyleSheet, type ViewProps } from 'react-native'\nimport { theme } from '../theme'\n\n// A surface card. Spread-through props so callers can add layout styles.\nexport function Card({ style, ...props }: ViewProps) {\n  return <View style={[styles.card, style]} {...props} />\n}\n\nconst styles = StyleSheet.create({\n  card: {\n    backgroundColor: theme.surface,\n    borderRadius: theme.radius,\n    borderWidth: 1,\n    borderColor: theme.border,\n    padding: 16,\n  },\n})\n",
    "src/components/TabBar.tsx": "import { View, Text, Pressable, StyleSheet } from 'react-native'\nimport { theme } from '../theme'\nimport type { TabKey } from '../data'\n\ninterface TabBarProps {\n  tabs: { key: TabKey; label: string; icon: string }[]\n  active: TabKey\n  onChange: (key: TabKey) => void\n}\n\nexport function TabBar({ tabs, active, onChange }: TabBarProps) {\n  return (\n    <View style={styles.bar}>\n      {tabs.map((t) => (\n        <Pressable key={t.key} style={styles.tab} onPress={() => onChange(t.key)}>\n          <Text style={styles.icon}>{t.icon}</Text>\n          <Text style={[styles.label, active === t.key && styles.activeLabel]}>\n            {t.label}\n          </Text>\n        </Pressable>\n      ))}\n    </View>\n  )\n}\n\nconst styles = StyleSheet.create({\n  bar: {\n    flexDirection: 'row',\n    backgroundColor: theme.surface,\n    borderTopWidth: 1,\n    borderTopColor: theme.border,\n    paddingTop: 10,\n    paddingBottom: 24,\n  },\n  tab: { flex: 1, alignItems: 'center', gap: 3 },\n  icon: { fontSize: 20 },\n  label: { fontSize: 11, fontWeight: '600', color: theme.muted },\n  activeLabel: { color: theme.primary },\n})\n",
    "src/data.ts": "// ============================================================\n// APP CONTENT — edit this file to make the app your own. The\n// app name, tabs, feed items and stats all come from here.\n// ============================================================\n\nexport const appName = 'NewLeaf'\nexport const appTagline = 'Your fresh start, one step at a time.'\n\nexport type TabKey = 'home' | 'activity' | 'profile'\n\nexport const tabs: { key: TabKey; label: string; icon: string }[] = [\n  { key: 'home', label: 'Home', icon: '🏠' },\n  { key: 'activity', label: 'Activity', icon: '📊' },\n  { key: 'profile', label: 'Profile', icon: '👤' },\n]\n\nexport interface FeedItem {\n  id: string\n  title: string\n  body: string\n  tag: string\n}\n\nexport const feed: FeedItem[] = [\n  { id: 'f1', title: 'Step 1 — Understand your options', body: 'Learn the paths available and which fits your situation.', tag: 'Guide' },\n  { id: 'f2', title: 'Gather your documents', body: 'A clear checklist of everything you need, in one place.', tag: 'Checklist' },\n  { id: 'f3', title: 'Find local help', body: 'Legal aid and credit-counseling resources near you.', tag: 'Resources' },\n  { id: 'f4', title: 'Rebuild your credit', body: 'Practical habits for a healthier financial future.', tag: 'Blog' },\n]\n\nexport interface Stat {\n  label: string\n  value: string\n}\n\nexport const stats: Stat[] = [\n  { label: 'Steps done', value: '3 / 7' },\n  { label: 'Documents', value: '5' },\n  { label: 'Resources saved', value: '8' },\n  { label: 'Days active', value: '12' },\n]\n",
    "src/screens/ActivityScreen.tsx": "import { ScrollView, View, Text, StyleSheet } from 'react-native'\nimport { theme } from '../theme'\nimport { stats } from '../data'\nimport { Card } from '../components/Card'\n\nexport function ActivityScreen() {\n  return (\n    <ScrollView contentContainerStyle={styles.content}>\n      <Text style={styles.h1}>Activity</Text>\n      <View style={styles.grid}>\n        {stats.map((s) => (\n          <Card key={s.label} style={styles.stat}>\n            <Text style={styles.value}>{s.value}</Text>\n            <Text style={styles.label}>{s.label}</Text>\n          </Card>\n        ))}\n      </View>\n    </ScrollView>\n  )\n}\n\nconst styles = StyleSheet.create({\n  content: { padding: 20, paddingTop: 64, gap: theme.gap },\n  h1: { fontSize: 28, fontWeight: '800', color: theme.text, marginBottom: 4 },\n  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: theme.gap },\n  stat: { width: '47%', gap: 2 },\n  value: { fontSize: 24, fontWeight: '800', color: theme.text },\n  label: { fontSize: 13, color: theme.muted },\n})\n",
    "src/screens/HomeScreen.tsx": "import { ScrollView, Text, StyleSheet } from 'react-native'\nimport { theme } from '../theme'\nimport { appName, appTagline, feed } from '../data'\nimport { Card } from '../components/Card'\n\nexport function HomeScreen() {\n  return (\n    <ScrollView contentContainerStyle={styles.content}>\n      <Text style={styles.h1}>{appName}</Text>\n      <Text style={styles.tagline}>{appTagline}</Text>\n      {feed.map((item) => (\n        <Card key={item.id} style={styles.item}>\n          <Text style={styles.tag}>{item.tag}</Text>\n          <Text style={styles.title}>{item.title}</Text>\n          <Text style={styles.body}>{item.body}</Text>\n        </Card>\n      ))}\n    </ScrollView>\n  )\n}\n\nconst styles = StyleSheet.create({\n  content: { padding: 20, paddingTop: 64, gap: theme.gap },\n  h1: { fontSize: 28, fontWeight: '800', color: theme.text },\n  tagline: { fontSize: 15, color: theme.muted, marginBottom: 6 },\n  item: { gap: 4 },\n  tag: { fontSize: 11, fontWeight: '700', color: theme.primary, letterSpacing: 0.5 },\n  title: { fontSize: 16, fontWeight: '700', color: theme.text },\n  body: { fontSize: 14, color: theme.muted, lineHeight: 20 },\n})\n",
    "src/screens/ProfileScreen.tsx": "import { ScrollView, View, Text, Pressable, StyleSheet } from 'react-native'\nimport { theme } from '../theme'\nimport { appName } from '../data'\nimport { Card } from '../components/Card'\n\nconst rows = ['Account', 'Notifications', 'Privacy', 'Help & support']\n\nexport function ProfileScreen() {\n  return (\n    <ScrollView contentContainerStyle={styles.content}>\n      <Text style={styles.h1}>Profile</Text>\n\n      <Card style={styles.profile}>\n        <View style={styles.avatar}>\n          <Text style={styles.avatarText}>YN</Text>\n        </View>\n        <View>\n          <Text style={styles.name}>Your Name</Text>\n          <Text style={styles.sub}>{appName} member</Text>\n        </View>\n      </Card>\n\n      <Card style={styles.list}>\n        {rows.map((r, i) => (\n          <Pressable\n            key={r}\n            style={[styles.row, i < rows.length - 1 && styles.rowBorder]}\n          >\n            <Text style={styles.rowText}>{r}</Text>\n            <Text style={styles.chevron}>›</Text>\n          </Pressable>\n        ))}\n      </Card>\n    </ScrollView>\n  )\n}\n\nconst styles = StyleSheet.create({\n  content: { padding: 20, paddingTop: 64, gap: theme.gap },\n  h1: { fontSize: 28, fontWeight: '800', color: theme.text, marginBottom: 4 },\n  profile: { flexDirection: 'row', alignItems: 'center', gap: 14 },\n  avatar: {\n    width: 52,\n    height: 52,\n    borderRadius: 26,\n    backgroundColor: theme.primary,\n    alignItems: 'center',\n    justifyContent: 'center',\n  },\n  avatarText: { color: theme.primaryText, fontWeight: '800', fontSize: 18 },\n  name: { fontSize: 16, fontWeight: '700', color: theme.text },\n  sub: { fontSize: 13, color: theme.muted },\n  list: { padding: 0 },\n  row: {\n    flexDirection: 'row',\n    justifyContent: 'space-between',\n    alignItems: 'center',\n    padding: 16,\n  },\n  rowBorder: { borderBottomWidth: 1, borderBottomColor: theme.border },\n  rowText: { fontSize: 15, color: theme.text },\n  chevron: { fontSize: 20, color: theme.muted },\n})\n",
    "src/theme.ts": "// ============================================================\n// THEME TOKENS — the customization surface. Change a value and\n// the whole app re-skins; screens read everything from here.\n// ============================================================\nexport const theme = {\n  bg: '#f4f5f7',\n  surface: '#ffffff',\n  text: '#14181f',\n  muted: '#6b7280',\n  border: '#e4e7ec',\n  primary: '#2f6df6',\n  primaryText: '#ffffff',\n  accent: '#16a34a',\n  radius: 16,\n  gap: 14,\n}\n",
    "tsconfig.json": "{\n  \"extends\": \"expo/tsconfig.base\",\n  \"compilerOptions\": {\n    \"strict\": true\n  }\n}\n"
  }
}
