// AUTO-GENERATED from template-build/tracker-app/ — do not hand-edit.
// Edit the source app there, then regenerate this file.

import type { WebsiteTemplate } from "./index"

export const TRACKER_APP_TEMPLATE: WebsiteTemplate = {
  "id": "tracker-app",
  "name": "Task Tracker App",
  "description": "A React (Vite) starter SPA: sidebar, stat cards, an add-task input, and a 3-column board with live state — add, advance, and delete tasks. Re-skin via index.css, re-content via data.ts.",
  "category": "app",
  "tags": [
    "app",
    "react",
    "vite",
    "spa",
    "tracker",
    "kanban",
    "interactive"
  ],
  "preview": "",
  "variables": {},
  "html": "",
  "buildTarget": "react",
  "files": {
    "index.html": "<!doctype html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"UTF-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n    <title>Task Tracker</title>\n  </head>\n  <body>\n    <div id=\"root\"></div>\n    <script type=\"module\" src=\"/src/main.tsx\"></script>\n  </body>\n</html>\n",
    "package.json": "{\n  \"name\": \"tracker-app\",\n  \"private\": true,\n  \"version\": \"1.0.0\",\n  \"type\": \"module\",\n  \"scripts\": {\n    \"dev\": \"vite\",\n    \"build\": \"vite build\",\n    \"preview\": \"vite preview\"\n  },\n  \"dependencies\": {\n    \"react\": \"^18.3.1\",\n    \"react-dom\": \"^18.3.1\"\n  },\n  \"devDependencies\": {\n    \"@types/react\": \"^18.3.12\",\n    \"@types/react-dom\": \"^18.3.1\",\n    \"@vitejs/plugin-react\": \"^4.3.4\",\n    \"typescript\": \"^5.6.3\",\n    \"vite\": \"^5.4.11\"\n  }\n}\n",
    "src/App.tsx": "import { useState } from 'react'\nimport { seedTasks, appName, type Task, type TaskStatus } from './data'\nimport { Sidebar } from './components/Sidebar'\nimport { StatBar } from './components/StatBar'\nimport { Board } from './components/Board'\n\nconst ORDER: TaskStatus[] = ['todo', 'doing', 'done']\n\nexport function App() {\n  const [tasks, setTasks] = useState<Task[]>(seedTasks)\n  const [draft, setDraft] = useState('')\n\n  const addTask = () => {\n    const title = draft.trim()\n    if (!title) return\n    setTasks((t) => [...t, { id: crypto.randomUUID(), title, status: 'todo' }])\n    setDraft('')\n  }\n\n  // Click a task's dot to advance it to the next column.\n  const cycle = (id: string) =>\n    setTasks((t) =>\n      t.map((x) =>\n        x.id === id\n          ? { ...x, status: ORDER[(ORDER.indexOf(x.status) + 1) % ORDER.length] }\n          : x,\n      ),\n    )\n\n  const remove = (id: string) => setTasks((t) => t.filter((x) => x.id !== id))\n\n  return (\n    <div className=\"app\">\n      <Sidebar />\n      <main className=\"main\">\n        <h1 className=\"h1\">{appName}</h1>\n        <p className=\"muted\">A starter React app — state, lists, and components, ready to extend.</p>\n\n        <StatBar tasks={tasks} />\n\n        <div className=\"addrow\">\n          <input\n            value={draft}\n            onChange={(e) => setDraft(e.target.value)}\n            onKeyDown={(e) => e.key === 'Enter' && addTask()}\n            placeholder=\"Add a task and press Enter…\"\n          />\n          <button className=\"btn\" onClick={addTask}>Add</button>\n        </div>\n\n        <Board tasks={tasks} onCycle={cycle} onRemove={remove} />\n      </main>\n    </div>\n  )\n}\n",
    "src/components/Board.tsx": "import { columns, type Task } from '../data'\n\ninterface BoardProps {\n  tasks: Task[]\n  onCycle: (id: string) => void\n  onRemove: (id: string) => void\n}\n\nexport function Board({ tasks, onCycle, onRemove }: BoardProps) {\n  return (\n    <div className=\"cols\">\n      {columns.map((col) => {\n        const items = tasks.filter((t) => t.status === col.key)\n        return (\n          <div className=\"col\" key={col.key}>\n            <h3>{col.label} · {items.length}</h3>\n            {items.length === 0 && (\n              <p className=\"muted\" style={{ fontSize: '0.85rem' }}>Nothing here yet.</p>\n            )}\n            {items.map((t) => (\n              <div className=\"task\" key={t.id}>\n                <button onClick={() => onCycle(t.id)} title=\"Move to next column\">○</button>\n                <span className={`title ${t.status === 'done' ? 'done' : ''}`}>{t.title}</span>\n                <button onClick={() => onRemove(t.id)} title=\"Delete\">✕</button>\n              </div>\n            ))}\n          </div>\n        )\n      })}\n    </div>\n  )\n}\n",
    "src/components/Sidebar.tsx": "import { appName } from '../data'\n\nexport function Sidebar() {\n  return (\n    <aside className=\"sidebar\">\n      <div className=\"sb-brand\">{appName}</div>\n      <nav>\n        <button className=\"sb-link active\">Board</button>\n        {/* Add more views here — they wire up like the Board above. */}\n        <button className=\"sb-link\">Archive</button>\n        <button className=\"sb-link\">Settings</button>\n      </nav>\n    </aside>\n  )\n}\n",
    "src/components/StatBar.tsx": "import type { Task, TaskStatus } from '../data'\n\nexport function StatBar({ tasks }: { tasks: Task[] }) {\n  const count = (s: TaskStatus) => tasks.filter((t) => t.status === s).length\n  const stats = [\n    { l: 'To do', n: count('todo') },\n    { l: 'In progress', n: count('doing') },\n    { l: 'Done', n: count('done') },\n    { l: 'Total', n: tasks.length },\n  ]\n  return (\n    <div className=\"statbar\">\n      {stats.map((s) => (\n        <div className=\"stat\" key={s.l}>\n          <div className=\"n\">{s.n}</div>\n          <div className=\"l\">{s.l}</div>\n        </div>\n      ))}\n    </div>\n  )\n}\n",
    "src/data.ts": "// ============================================================\n// APP DATA — edit this file to make the app your own. The app\n// name, the columns, and the seed tasks all come from here.\n// ============================================================\n\nexport type TaskStatus = 'todo' | 'doing' | 'done'\n\nexport interface Task {\n  id: string\n  title: string\n  status: TaskStatus\n}\n\nexport const appName = 'Task Tracker'\n\nexport const columns: { key: TaskStatus; label: string }[] = [\n  { key: 'todo', label: 'To do' },\n  { key: 'doing', label: 'In progress' },\n  { key: 'done', label: 'Done' },\n]\n\nexport const seedTasks: Task[] = [\n  { id: 't1', title: 'Sketch the landing page', status: 'done' },\n  { id: 't2', title: 'Write the onboarding copy', status: 'doing' },\n  { id: 't3', title: 'Wire up the signup form', status: 'doing' },\n  { id: 't4', title: 'Add pricing tiers', status: 'todo' },\n  { id: 't5', title: 'Draft the launch announcement', status: 'todo' },\n]\n",
    "src/index.css": "/* ============================================================\n   THEME TOKENS — the customization surface. Edit these and the\n   whole app re-skins; no component changes needed.\n   ============================================================ */\n:root {\n  --bg: #f6f7f9;\n  --surface: #ffffff;\n  --text: #14181f;\n  --muted: #5b6472;\n  --border: #e4e7ec;\n  --primary: #2f6df6;\n  --primary-text: #ffffff;\n  --radius: 12px;\n  --font: ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, sans-serif;\n}\n\n* { box-sizing: border-box; margin: 0; padding: 0; }\nbody { font-family: var(--font); background: var(--bg); color: var(--text); }\n\n.app { display: flex; min-height: 100vh; }\n.sidebar {\n  width: 200px;\n  flex: none;\n  background: var(--surface);\n  border-right: 1px solid var(--border);\n  padding: 22px 14px;\n}\n.sb-brand { font-weight: 700; font-size: 1.1rem; padding: 0 8px 18px; }\n.sb-link {\n  display: block;\n  width: 100%;\n  text-align: left;\n  padding: 9px 10px;\n  border: 0;\n  background: transparent;\n  border-radius: 8px;\n  color: var(--muted);\n  font: inherit;\n  font-weight: 500;\n  cursor: pointer;\n}\n.sb-link:hover { background: var(--bg); color: var(--text); }\n.sb-link.active { background: color-mix(in srgb, var(--primary) 12%, transparent); color: var(--primary); }\n\n.main { flex: 1; padding: 28px 32px; }\n.h1 { font-size: 1.5rem; letter-spacing: -0.02em; margin-bottom: 4px; }\n.muted { color: var(--muted); }\n\n.statbar { display: flex; gap: 14px; margin: 20px 0 26px; flex-wrap: wrap; }\n.stat {\n  background: var(--surface);\n  border: 1px solid var(--border);\n  border-radius: var(--radius);\n  padding: 14px 18px;\n  min-width: 130px;\n}\n.stat .n { font-size: 1.5rem; font-weight: 700; }\n.stat .l { font-size: 0.82rem; color: var(--muted); }\n\n.addrow { display: flex; gap: 8px; margin-bottom: 18px; }\n.addrow input {\n  flex: 1;\n  padding: 10px 12px;\n  border: 1px solid var(--border);\n  border-radius: var(--radius);\n  font: inherit;\n}\n.btn {\n  padding: 10px 18px;\n  border: 1px solid transparent;\n  border-radius: var(--radius);\n  background: var(--primary);\n  color: var(--primary-text);\n  font: inherit;\n  font-weight: 600;\n  cursor: pointer;\n}\n\n.cols { display: grid; gap: 16px; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); }\n.col { background: var(--surface); border: 1px solid var(--border); border-radius: var(--radius); padding: 14px; }\n.col h3 { font-size: 0.95rem; margin-bottom: 10px; }\n.task {\n  background: var(--bg);\n  border: 1px solid var(--border);\n  border-radius: 8px;\n  padding: 10px 12px;\n  margin-bottom: 8px;\n  display: flex;\n  align-items: center;\n  gap: 10px;\n}\n.task button { border: 0; background: transparent; cursor: pointer; color: var(--muted); font-size: 1rem; }\n.task .title { flex: 1; font-size: 0.92rem; }\n.task .done { text-decoration: line-through; color: var(--muted); }\n",
    "src/main.tsx": "import React from 'react'\nimport ReactDOM from 'react-dom/client'\nimport './index.css'\nimport { App } from './App'\n\nReactDOM.createRoot(document.getElementById('root')!).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>,\n)\n",
    "tsconfig.json": "{\n  \"compilerOptions\": {\n    \"target\": \"ES2020\",\n    \"useDefineForClassFields\": true,\n    \"lib\": [\"ES2020\", \"DOM\", \"DOM.Iterable\"],\n    \"module\": \"ESNext\",\n    \"skipLibCheck\": true,\n    \"moduleResolution\": \"bundler\",\n    \"allowImportingTsExtensions\": true,\n    \"isolatedModules\": true,\n    \"moduleDetection\": \"force\",\n    \"noEmit\": true,\n    \"jsx\": \"react-jsx\",\n    \"strict\": true,\n    \"noUnusedLocals\": false,\n    \"noFallthroughCasesInSwitch\": true\n  },\n  \"include\": [\"src\"]\n}\n",
    "vite.config.ts": "import { defineConfig } from 'vite'\nimport react from '@vitejs/plugin-react'\n\n// Vite + React SPA — light and fast, boots reliably in the WebContainer.\nexport default defineConfig({\n  plugins: [react()],\n})\n"
  }
}
