'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, Download, Rocket, Trash2, Loader2, Mail } from 'lucide-react'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { FileTree } from '@/components/builder/FileTree'
import { CodeViewer } from '@/components/builder/CodeViewer'
import { DeploymentDialog } from '@/components/deploy/DeploymentDialog'

interface Project {
  _id: string
  name: string
  description: string
  type: string
  status: string
  files: Array<{
    path: string
    content: string
    language: string
    generatedBy: string
  }>
  aiAgent: string
  createdAt: string
  updatedAt: string
}

export default function ProjectDetailPage({ params }: { params: { id: string } }) {
  const router = useRouter()
  const [project, setProject] = useState<Project | null>(null)
  const [selectedFile, setSelectedFile] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    fetchProject()
  }, [params.id])

  const fetchProject = async () => {
    try {
      const response = await fetch(`/api/projects/${params.id}`)
      if (!response.ok) throw new Error('Failed to fetch project')
      
      const data = await response.json()
      setProject(data.project)
      
      // Auto-select first file
      if (data.project.files && data.project.files.length > 0) {
        setSelectedFile(data.project.files[0].path)
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred')
    } finally {
      setLoading(false)
    }
  }

  const handleDelete = async () => {
    if (!confirm('Are you sure you want to delete this project?')) return

    try {
      const response = await fetch(`/api/projects/${params.id}`, {
        method: 'DELETE',
      })
      if (!response.ok) throw new Error('Failed to delete project')
      
      router.push('/dashboard/projects')
    } catch (err) {
      alert('Failed to delete project')
    }
  }

  const handleDownload = () => {
    if (!project) return

    // Create a simple zip-like structure (for demo purposes)
    const content = project.files
      .map((file) => `\n\n=== ${file.path} ===\n${file.content}`)
      .join('\n')

    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${project.name.replace(/\s+/g, '-')}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    )
  }

  if (error || !project) {
    return (
      <div className="p-8">
        <Card>
          <CardContent className="pt-6">
            <p className="text-center text-red-500">{error || 'Project not found'}</p>
            <div className="text-center mt-4">
              <Button onClick={() => router.push('/dashboard/projects')}>
                Back to Projects
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    )
  }

  const selectedFileData = project.files.find((f) => f.path === selectedFile)

  return (
    <div className="h-screen flex flex-col">
      {/* Header */}
      <header className="bg-card border-b px-6 py-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Button
              variant="ghost"
              size="sm"
              onClick={() => router.push('/dashboard/projects')}
            >
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back
            </Button>
            <div>
              <h1 className="text-xl font-bold">{project.name}</h1>
              <p className="text-sm text-muted-foreground">
                {project.type.replace('-', ' ')} • Generated by {project.aiAgent}
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Link href={`/dashboard/projects/${params.id}/submissions`}>
              <Button variant="outline" size="sm">
                <Mail className="h-4 w-4 mr-2" />
                Submissions
              </Button>
            </Link>
            <Button variant="outline" size="sm" onClick={handleDownload}>
              <Download className="h-4 w-4 mr-2" />
              Download
            </Button>
            <DeploymentDialog
              projectId={params.id}
              projectName={project.name}
              onSuccess={fetchProject}
            />
            <Button variant="outline" size="sm" onClick={handleDelete}>
              <Trash2 className="h-4 w-4 mr-2" />
              Delete
            </Button>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <div className="flex-1 overflow-hidden">
        {project.status === 'generating' ? (
          <div className="flex items-center justify-center h-full">
            <Card>
              <CardContent className="pt-6">
                <div className="text-center">
                  <Loader2 className="h-12 w-12 animate-spin text-primary mx-auto mb-4" />
                  <p className="text-lg font-medium">Generating your project...</p>
                  <p className="text-sm text-muted-foreground mt-2">
                    This may take a minute
                  </p>
                </div>
              </CardContent>
            </Card>
          </div>
        ) : project.status === 'failed' ? (
          <div className="flex items-center justify-center h-full">
            <Card>
              <CardContent className="pt-6">
                <div className="text-center">
                  <p className="text-lg font-medium text-red-500 mb-2">
                    Generation Failed
                  </p>
                  <p className="text-sm text-muted-foreground">
                    There was an error generating your project. Please try again.
                  </p>
                </div>
              </CardContent>
            </Card>
          </div>
        ) : project.files.length === 0 ? (
          <div className="flex items-center justify-center h-full">
            <Card>
              <CardContent className="pt-6">
                <p className="text-center text-muted-foreground">
                  No files generated yet
                </p>
              </CardContent>
            </Card>
          </div>
        ) : (
          <div className="grid grid-cols-4 gap-4 h-full p-6">
            {/* File Tree */}
            <div className="col-span-1 overflow-auto">
              <FileTree
                files={project.files}
                selectedFile={selectedFile}
                onFileSelect={setSelectedFile}
              />
            </div>

            {/* Code Viewer */}
            <div className="col-span-3 overflow-auto">
              <CodeViewer file={selectedFileData || null} />
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
